# Generated by Django 5.0.7 on 2024-08-16 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('projects_per_month', models.CharField(blank=True, max_length=255, null=True)),
                ('average_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('hours_per_week', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
