# Generated by Django 4.2.7 on 2025-07-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_project_payment_monthlygoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='survey_filled',
        ),
        migrations.DeleteModel(
            name='UserOnboardingData',
        ),
    ]
